
name: Matrix-Test


on:
  
  workflow_dispatch:
  pull_request:
  merge_group:

concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: job-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Show GitHub context   
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}   
        run: echo "$GITHUB_CONTEXT"
        shell: bash

