
name: Matrix-Test


on:
  
  workflow_dispatch:
#  push:

jobs:
  test:
    strategy:
      matrix:
        job: [1, 2, 3]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: The random failing job
        run: |
          exit $((RANDOM % 2))
