name: Build Docker Image

on:
  push:
    branches:
      - main  # Adjust with your branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [1.2,3,4,5,6,7,8,9,10]  # Define the versions or environments
        os-version: [1.2,3,4,5,6,7,8,9,10]  # Define the versions or environments
      max-parallel: 3

    steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
    
