name: Hosted

on: [workflow_dispatch]

jobs:
  build:
    runs-on: [ubuntu-latest,self-hosted,jkj]
    strategy:
      matrix:
        node-version: [1]  # Define the versions or environments
        os-version: [1]  # Define the versions or environments
      max-parallel: 5

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello!;sleep 30
    
