
name: Matrix-Test


on:
  
  workflow_dispatch:
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Show GitHub context   
        env: 
          GITHUB_REF: ${{ github.ref }}
        run: |
           echo $GITHUB_REF
        shell: bash

