
name: Matrix-Test


on:
  
  workflow_dispatch:
  pull_request:
  merge_group:

concurrency:
      group: run-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}--${{ github.workflow }}-
      cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}-${{ github.ref }}-${{ github.workflow }}--${{ github.workflow }}-
      cancel-in-progress: true

    steps:
      - name: The random failing job
        run: |
          #!/bin/bash

          echo "GitHub Event:"
          echo "${{ github.event }}" | jq .
