name: Build Docker Image

on:
  push:
    branches:
      - main  # Adjust with your branch

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.3  # Updated to the latest version&#8203;``【oaicite:1】``&#8203;

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0  # Updated to the latest version&#8203;``【oaicite:0】``&#8203;

    - name: Build Docker image
      run: docker build -t my-image -f Dockerfile .

    - name: Display image size
      run: docker images my-image --format "{{.Size}}"
