name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Generate a random number between -10 and 10 and validate it in the same step
      - name: Generate a random number and validate
        run: |
          echo "Showing error"
          echo "::error file=app.js,line=10,col=15::Random error"
          exit 0
