name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Generate a random number between -10 and 10
      - name: Generate a random number
        id: random-number
        run: echo "::set-output name=value::$(shuf -i -10-10 -n 1)"

      # Check if the random number is negative or positive
      - name: Check if the random number is negative or positive
        run: |
          if [ ${{ steps.random-number.outputs.value }} -lt 0 ]
          then
            echo "The random number is negative. The job will succeed."
            exit 0
          else
            echo "The random number is positive. The job will fail."
            exit 1
          fi
