name: Greetings

on: [pull_request_target, issues, workflow_dispatch]

jobs:
  greeting:
    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello!
